uni_email: ENC[AES256_GCM,data:tWJawUqBZ+hboaahIJGIo3kcGp2Yc4wXXFDyx/CLLQ==,iv:e48bxt8wgJRCZ+joYNaYXxRsFnPRxYqX66KN7mj2vcs=,tag:dDOhPj6efwK9dbIkUysJVg==,type:str]
full_name: ENC[AES256_GCM,data:STc8fS46fT1N0w+yGzlHIg==,iv:VXltx/pPwujfK6YaSjUZ2lRsk/jVUk5hHIHilLqDwlw=,tag:9kirD9oszDT0rl3Sss0MIg==,type:str]
coordinates: ENC[AES256_GCM,data:aa+OX+RydXTG0RAv79u2,iv:wEV5BjWP4EAaDxL/mmw0DeG7ZshRXqn1a2tz804srEc=,tag:wrBKS3RaFfJhP1VvDIk6WA==,type:str]
server_vpn_endpoint: ENC[AES256_GCM,data:qXk/uAUtPQFJYcI=,iv:SzIVmuNyJnx/9yvBlCzbXJfJwZjHqPMC8oZ/kepn6VU=,tag:CjjtDakL0NF6F8TEe0uF+A==,type:str]
home_ssid: ENC[AES256_GCM,data:A4JvRuxRv/X3DUhzRMU=,iv:Gg1UTqqUywxDFCqvgA7YDWCVkUpqbEm/SgoLjPV6LUc=,tag:wTKcMkCZAcnxtK6zsYSdAw==,type:str]
user_pw: ENC[AES256_GCM,data:xVJ6O2o/+ltbyOfjTPyjqx7NmqB9R5B/4Jb0EENhdkHC6GiFmNppExtRwDaXH82ZayQAKCaEkJ+gdpiMqQ7Th1Z5661I/Eh6RQ==,iv:1xTltuY5j0r+sR+sHXGQYuaPXq5QC7XHrPAiLShfxLQ=,tag:PRNhp6cO8HkHv7PZGRIMaQ==,type:str]
root_pw: ENC[AES256_GCM,data:XlUI8yRtVw3PTy4f0tTVW0VlDwo+46oxezQbP4fTDOZ5ylJEuoO2MzAaGaPgdCJuQCBgF8fGzxbqcokn3BpKayVNYXDZUk+xXg==,iv:2J5P/7Gl4Qbj04/Eh0AkbaD/QTvTesmBl2U1GAJUxzs=,tag:n+u/GFSzGsp9dkcX0pE04A==,type:str]
syncthing_pw: ENC[AES256_GCM,data:Ln4F4UTxr0scoZzoGrv9uk500g==,iv:sCL3SLKEARzA9YdRW8VVPmuIToSpSkQkUwY7v2s/cU4=,tag:jDnDQHOogKG1FXeLpI1ndA==,type:str]
attic_access_token: ENC[AES256_GCM,data:ZlR+620/olgj1/Nt60FAfTCVRGUFUFWXpQ465O4UTxCuRFjYVZ6z8j2zQM3Tb177hgmcLI5vG75g9JLf5wuueZK7aIh/ncTkBfZefBLPSVCU1W9wszkG6Fvm8nnnxAIkhXYQ5pCJZgzhOR818HJzdLPZIKTzziVI0tyhqi0mafaIA9Wrpc5I9Glga/Y2MLG/jqaEI4pipjDDPjqh4zF+UBcIFwevog6uFEukPex4m4IFFTyWej1Q6cHf00Cozy4RTgAZaEjEflVab7FBwDEVTlg0SreZEnlByKoRmJeu4bOV/Gm9vgmcIddtAiPL2XPR4O5PX8jRpUhqFVQfJpz4mkNsT4ywhBgDhVKZkSjnjLTD2ZO32mx5FdzaguHtH4HQgTIBwIiOqEMG5PsdsOkAswxluNShFlSVnzTnrgIuOqiTVmtyO41TSUW+uDdbAklvuSJNZ9NACdmTve/8tNMx6KXd76ZUQ9M/MiTAyOVIE0Y/jQ0bKy9oUERBxiBdRca430pp1ztn5IVRgms9cXOW3B4cEZle5U5joLEetWDCHFxeF7B8zfYFfeF8L9LOsN0KDAI0G/3G6TnBrrlmQFTSTzvf7eLW48XEPsczuqJTOGh3m1giQOiQ85mBnyz3wfPugxV14ga0hPZKhnPvsLoLY8XyTPTxQcEr2AJ2fwYdbq47zAFAFUgJYSiQifIqzX5ctv1BEQb57s7ydoe7VLDYcfMOQOtKIpt3efWs+vrhpcDVQ4hlCJusFHWSOMt01RM8XddLGCbF0mj61ZsQpMnNYjv35jzjeg1qrMCyuTFRim/nTh34di/fuTSvi7QPxOw9qTcw8XBjVM7sFxzo3s+3lkJ/zSxbX1xrRfpEA7xgH0ookFo69H6RkCdMJTBJn+reqzAlViYkEFS0OF/aHkof4bmd08DVfGDzvtBYtzf0lb3BRRFmBPzKrgCn0w0iq84+aefZSMGZv0XaSQ0WQDOoof06pk6GvSnW+y7A1v/WiLqkFbvbNNpouC/ytoHLuavGHl0IaRuhcmNY+rZM2xKTNRJZSYntqSxS9YAviFeL0BA+ot63hogke4BuiufAXbx3k3pihNw3Vo9x5RTEHYJYXm4/NAqrL+4qohtrBoWKn4DMrv/VaLUoW75ratqrQitDtZUOb+Dg7tc=,iv:bGd5MBWcGcspyhGd6j4E8PZCQl1fyFCSY41XV8XYOF4=,tag:bBhGEonAPAQxGOzb7BT1/Q==,type:str]
calendar_pw: ENC[AES256_GCM,data:dsvgvcEEWd1XzbrTOL3Sf1Ti51I=,iv:n/gNK0XLWWIMXO3sNiGqC2wc5L8txIQqZimY3flKHIQ=,tag:kswSwMfMg35kdeHzCXZZsg==,type:str]
github_token: ENC[AES256_GCM,data:Zg6HXmrI/mFLZkHQazgiwDrYk+0NJAVqLL6VvgwERNSJIL80KcmuWA==,iv:KXFBHi7QCEPj+6mqHF1txisdLHkAYUJ5CMA/MDQsrDM=,tag:AeJ8fG2JXC5xBf8pbPurTQ==,type:str]
airvpn:
    pk: ENC[AES256_GCM,data:BH5D8PZnKV6HIhbZdyu2Wuv0gDjPIHFEn2+GuF3UngINTfTjo/QTja397A4=,iv:EgDaI6+3AL8I/DgqI8jr58i8VvuAorgVZ7UyW6ABo+o=,tag:Uhoo61JQhkMFZ3lJ4RexUw==,type:str]
    psk: ENC[AES256_GCM,data:Jr+9t/65FllLlAoCStBvJQR2wldSokX5+1pRKjsDpyRCXzLwnYp4QUoXJos=,iv:SlwvLt/FDhxf/8x97VNnRclsGz+n12uKXruTQT+B0lw=,tag:+iZUAUxekkkaTNZCak/mcQ==,type:str]
    sk: ENC[AES256_GCM,data:RPd4waI28P2N7EM0WRQR8cOSTqHzd4eHFM1oL1T3gUaXuoRQE9GzGXIEwzc=,iv:Af45O4/8gdmpc4ExrnGFjLT/Z3g+WCccR0pWNBTxEJ8=,tag:x9sJh08ohy4LNQmnglnuOQ==,type:str]
tailscale_auth_key: ENC[AES256_GCM,data:qx/2/XNK3XTe3sL3WoGLtYo8RJJx1sJHHcA77ym7twxFy1mSwwdg+WeAkxD12vW+Kj5UXkQ25eJp8wkMerJkkeVG6EB9uh8Ssd9q0E+A0Q==,iv:nnzDY4/OqcvzvjzFp1qQXdNV8xF6jb75IML4gBDV4VQ=,tag:yeMuqgNsgKmmCvYoF1WqFg==,type:str]
shannon:
    vpn:
        psk: ENC[AES256_GCM,data:mzsmx02K/79lLkbAOQLpWUo2DWx9FK1MitMLRyHAHAq6KhwBvVVFFXNejFo=,iv:hbqUOA7HymgorHsZdhkVnC+y1Yc6tVXFJtEF7tKbRQs=,tag:QfTjNGYFTJMA2+V+SMLuBQ==,type:str]
yoshino:
    vpn:
        psk: ENC[AES256_GCM,data:VANlVITsFcl/RcydhweR7t6vB6p5jiMP1NJn7/kT48sulyk6C4n5utC3C2o=,iv:FVeY3pBIRBUnXA8l9/BBKagX5jun6NpZ0ydXDjOmdfI=,tag:m5zMX2R2mXtZgmkmwXghtg==,type:str]
lamarr:
    vpn:
        psk: ENC[AES256_GCM,data:JgCv9BDJZLnCn4E/OZqDI1wps1Mo+NT2j8w9n6v3QogiaynO93oFSvRPO2o=,iv:KSDze9igkQt2qFCgt5bSNzzchZ0W+y6LT+2CdKJ7KYo=,tag:h3beFVbsDTik1770ryrY5g==,type:str]
cray:
    vpn:
        psk: ENC[AES256_GCM,data:6rVacTDm7TpoxQHFHCPDUxWFDis87Ggn0cBqzqRufYwvip2U1vQb24JgOGc=,iv:zXwapLDlzdzElAhHaWstknY+dp+M3JS9YwdabFpbms8=,tag:NNb2xW/AWwfDCprBKZilew==,type:str]
mach:
    vpn:
        psk: ENC[AES256_GCM,data:eIBR/DTNpPDR7Oe+A2WPPKVIJtmqZZe4MqNtIGjY/zBTAeEc0VxDG/gm4Z4=,iv:G6+Ho3wSi/i09AZ+fT8D/ZHYA3wKwB0MgfmUb5tO3Ik=,tag:8DFJdJf2wS+GDSb01B234A==,type:str]
naitoh:
    vpn:
        psk: ENC[AES256_GCM,data:cJ1Ip4Wgis0oKAR5hdvZUGq337RWiY3utnDLB9OIqJ/0redSX22XoXzmAoI=,iv:5WHSn9jSPC68VGvrueYLz61HgHaFeEHh9Xko6BGg7XE=,tag:o3yqOU94ACM3BJWiS66Wsw==,type:str]
woz:
    vpn:
        psk: ENC[AES256_GCM,data:dVgLo9G5zIvTuTF7ytLzsKRYVnzgT/dyyUGHcjNI+MD3S3NJwSNDW39iLRk=,iv:N+NDM/495cm72NXpKzob6it9sGbTO2aidYgnQlPnuBg=,tag:U36DqyV7tMSzdxYd9sYjbw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDlPQ2pVREhh
            MEhSYnlveTNsd2N2b0VWc2cvbHRtTkFqS0ZPRlZlbGk1UzkrNjNNMGRTbkhmNzMz
            ZisvVXhndjZyWjQ5dEk2dnprME1jMFd5T0g2UWFQNERLVFpxUEF0bno1MzdkZHFu
            ZnVKbisvK3ZsU1lZZEFMbkF6OWxGVy96eFlPRHBCdDgybldqSSs4Wm5mb3AxYTZk
            eklhKzBJS21Kd2RYRTJvOVVrMXZJMjlQTms3eU5nQzlOcG5EaElPa3dNQ2s1ZmNI
            UWtJbGFjTGNubVc2bUJ0NWF0elgrblhrUWphdVhTZUJrWlNuYXNMVHd4WXFiUWNl
            RHhNWDRiRnRoSndRSzNIQlVpMlBIUlRMbGNxeXN2Z1libTNCemFQSlBFRkVxUFhr
            Y3JnWGJad21SbjRBdFgxUHlUSUVtN2R1cEZUUmpoeVkwWER1U3JiczYvNkI5S1My
            NXFSUlNWNGZQMjM5MmNPdzJQY2VDRWRCOWlSdXRidnpaNXIwSnE3MmFSb0hNdWFL
            UElrZHpYOTNsRzIrRjJ4dEtXL05YRURsdzlVdVUzRm1pQ3VHYmJabUtHWG9EcVpR
            anI2TkhwanNMd1JyY25JSXFvMXFHLzU4SUUvL1E5T2hnbDI2ZVBJTk9UWUs0akx0
            SnpudUlVM2RhWG1Fak50MmRuVUQwMTJjcEx3NHkxRXdlUlZZWlFqYUhQZ2RvY1NL
            RFJaNHBHWUxpTm1LN0IyMG1SQ01PQ0ZQU290Y0tkWlNoUXFsdlN3aksvVUlDSkZF
            cEVIa0ZXVE5XUTI1bU5PSjdxVmlNK3pvVVZLdDNtWnZodXg5RWxyTngyQmVPQ0dS
            YXJwWmZnaDNXNEQxSlRYa3dnaExpUWROaEZXV3ozWDdTSmsrd1FMTDgvem5SZkRm
            cFVrYUZSaTE5OUpvWlAvT1FFS2x0MDV6Nk44aU44VlIvUFpEL0htbHlhTFJHSGFS
            RUNneFo5VTY2amErWjM4WDdlL3kzT2ViYVlHZkxpMWovSUMxck5uZjk2c0ovWjhh
            RjRRbzFQUzRMWTNLNDl2OFl0dUZMNU1pR2VCa09ua3ZWeHVlTHg4REgrY3oxY1NJ
            dTJ5dnFjRGJTSml2M2NVS2JFUkxQSUJuMVNxb2ZEbVI0c25YbHRYNnBjQTVMbXg2
            T0x0aUF6MTI3cHJwQldvK0hxRjFRdFRoYTdjYkxDWGpjRnRPSHZCNXkzMFBhbjU4
            Vk9JanZYbjVPM3RwTFNKbkwyTUVvQkJFR09YcnVVZXQ3VSt4Z1dJbUpDdzRQa1pJ
            T0p6VmtieTUxTU1BaGZleXVweWJmd2xSUUx4azVhdk8vTXRJS1NKTHhtcHFycWZO
            REdGRkhsWmZTQU5rRkZET3FVbHJMOGEvdENHZmtFVlJCYjUvcGZJMkdPOUVJenlx
            MXEwVk1OQkVJdjA1MEY4YVQwSVZ4dDE3RlRnTHZPMW8zZGFtSVQ1bUhRd2lxMVB0
            aXJNeFdYNCtjdldjay8vUGVjV2VBV2ZEWkhkOEtuMVI0SW1VSnJZRUdyOGc2WmN3
            NWtaMnZtRnZqUitYSFVlelFqUnBDTktsaElRS3ZNazBoOXZZWVFtM2ZjaExjdEVr
            OVlQbzFpVDNaUERZU3FSNGp1UzVpQ0ZmRVBEU2JWV0drcVY0ZVZFdy9ib0VRUXhp
            b3J4T2k5REMwVUdiVnZQUUUwbS9tWU0yakpYZkQ1V2tIVDd6WWdPU0ZtbFNvV0xi
            cmRWbmRZUVVoeXozeHk2Y2hZRXk1dG1EQ3FLNXh3elBmTzlRd0hyYWtKYkRLUlJ1
            NTZFelpkbFhUQUV4TFVLNnYyL2J1N3I2ZGs1aHZjN0J1UkViaW0yK1V5TjUwaHV2
            R2VIeVAxem5aRFV4bFB2VFcwZkVqVnNnUXNXb3AxNStRWGVVSDFJOWRRU0RzZ1ZI
            OVAycDBxSWNINkthN2kvdmZtTzMxcG92WXp2aHIrOGdVdHhOcWZ0SlY2d2RFQQor
            MHFMN3AwaFR2ZHQ0alhnQ1JFeFhwWWtmODFLOWFsYVBDQ2t0V0Y2M3MwCi0tLSBK
            ZUJMeDh6dHpnM2dsbklGbTFxQXhYN0dwYlE4ZDhITDdyU3NaQXN4bS93ChIdl9OO
            4DSIzWP5D9lOecSRMPGOxNYSi79GFcwseZH2cEd27Zu7gwBFPTBmuVPNeBahHB2q
            49RU22LgFmJ++aU=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq15zkgrl6kqmch899ejsehzdqvyudyz33uq65njscappkvfqm4tqermjgud0rddvq4rpryr5r5jx35c844fsr7245k72jtd755tdqmt6jgv84pt2g6kz0plkugknvr6s84x5f9s906qdlrwsmjveyu3egvv8mxhvfxhxtpw9qqvwmt7uf8jtk6sq7xgk49yau46ufr8qf2q05ycjyxvf57hpsrvlr2ylj3jg6j59uknsc8xsexvfrmwaar02w43wdfdwjz6x2pklycp5fr4za4zm3s0scyz5u00nrpgrr2sqwqn03xusjredazgsy5qrwjgy6jk06rhxp7cxs86w4h0gqtpewmes8yk5lhfjdajwucv8tr2nh049vtas8r5yplykjt96u2pm405wmuk3zrkgc2lwm5jnq222ur5vc3aqlee6qpdkdne69tcr7jv4j9vfwppzqnzwanane3qmd2dtvgc9nxugxz0z4m0mexrwtmt00vxqena4cteafexcumhe2q3sfqwzml674gt3p66xpx29hg03yhpqx372axnungrkqxcn5qtz58rqaqe79cgpu9pnkmdl2x24uyxv7l4au5ksgy64jpdq9df8m4nga3x3ya6qnpddgt9wph26g4wzv6sqs4qk9h68hjsdm4gc64u9cscvuakemx0sx9gke7pxwwwjulj5jednz63rcsq2hdnpdvcycfv74q6jgves8xnd6wxyx3j37a7m9hs4ezehkfj0mt240qza80u59x0e4j6c8sk7gwxkvwxw5fs2vzu9yvvnk4y2cckceww8pm5ygjp7fse2zsgl3hvrlyklrw5a9f3td4ynsufj3zx8q5k676gt9ggdnr2jy3pvp6qs7hgmqfc2j0n5kxzk2xxg292p7tsh88h3g9uy526wdps3tmzprvycwagk3xz6s6s67sv0rkf94axasegfrfd02cwvfn3ag0ej2my9f882rly5tfpsw4f27fxqm9qqsxzxtgdt69qxs2p2z699q9keu3ak3h8vu9k6av83dsn8pqk6qs343fyfyvmmhrfdrtf9uujerwapvc85n2cj0s4l0cts03ts2d3u4kah53kvl8r5clt9gsckcdnuuj9a428s463gqlcxlkwq2vp2p0qctcepzzykezclvvuf3x04av0da3t32mq2mztv96eppakknczh94hrved7ya276s9t97wxn7tn9m83c945zhz49yseu4k76lcmfesudc2u9hd9azshxzc2d90zee03lhqrltj5xgs7dlpm9d25j9avfzg25v0zw4zzdxm2att6gmu3d5zeaaj9zv3vw28wvp8pdzmq9k5r348th5l0qv2jrgx5y3qfpndzvuz34uz3fkk3vdky32g7yesg2scuf7kgr2uszf925333g3kgjp4x396fns4wzhlap6slfh537qqlxwdgv05u4kaff9hwtpp0hzp2ks0g3hpvugm5u8h3scdq08yxyxa9esm2fnf3sgterqxy8kjaxzcyd48evlehnsss4e34v89s3sy4qa5q2qh5jz7sykjmha5enke9hpdry6d5k9us7h2d5szklegwfkgz48krs5epfc0kz7dfjvqw85m8r0x84kejge4huesztw0yrarw9x3ug99uh2qd7y5lkw0v8e069ptd29pmhshehngt5zu625aftxf7crawgkzeckz5hhdqq6jd5ftqzcupme0nzhql3c4s3cn5gl58muqrnjj45qfvlfaz5xc5d9znpu2dfec5v5qz0mlrq4ehyltj3gdnrn8893vmmuhty686z8u8jxzrlgj3em80rfazqwqhnscnh8x2qlwhs8f0u044fjh4h73e862fe9xg8cwqu2f290tc8mgedckg5tj7mdwz2nfkkl7t3yxmx7ukza3xwhauqpt3s7vzdezyqx9tqv
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGk1RmhPdFh1
            dks1VUpuMlJWZ21MYnNiS0lJamMwWFZXZWNxcjVUbWc0NFVjZE5jMWd3WE51THRE
            K1dzUmlwU1U1MVhHUzYyS0VMUHA3MTByZmhVNEx4a2lobHNGWjlnMEU5K1V5R3o0
            QWNaYmVGVGhzWFRsNUsvRHk3NWRGa1hKNXpweDBPa00wVlBtMUt1aTBadG5ScnFG
            MkRzWWVNUlRXYUJTL1l6YmQvdzN2K293dU1Vbm0zMk4wY2h1SFVrL0hITHRFY3lh
            Y1VqckVGQ0ozSmxmNDl6Ymo4RXloM2piaWZTc2djai9iTFN6T2p0YzB2NkRuZkQr
            d2RIc1NESmNUWWdOQ0xRUmlkK096K01KYksxZnZIVjNWbHNENEtVb3lheVpFWWQw
            Yys2ZUZxd3MvOFNBeUxCSGN1RnhhZGxITVF4MkdyL3NTUDlTRlVneFpWNDh0TXpJ
            YmhCbEZNd2hZSFg5SjBhUlVFQmpPQjNjQi9pam1kRktUK3RMdnhQZC9YTGxZMXhi
            VVFyZGFpZTVsTEsvbE12amhvUFpkRldpb1I5ZkRRbzNxVEorb3lNYmduaHlGd1Bh
            VmZEZnd3MkMzVTlxUDRHdTgxeFhwbVRKOVFZbys0RTVMcVBIZVVXNCsrQzNCdEFr
            WXQ0aUg5dmlwMDFBR1R5TjNFV3M5cVI4aFVuRHJhdEVGcFc2N0M0SUhoNkpBN2hW
            UWpuLzM4UVhKRTNMZEtZMTFBTytob3g0WitoZjNKZE5UZWZ1cnN0QXVXamVhRTBM
            N3NoajRweEcwOWJYUk1hZWFGeHhzNkxiWTUyVnBPVWZDaHZsS29MeDBxUGFLWFFX
            TE5neTQ3bmljSzd2V3p1enBCZnlzQ0k2MlluV3F5MytDL2pWaml4OElvazhEaEtQ
            dkVlUGRXSnIxTTlCeFA1ZTlNOERvWGpIQU5hdk1tT0ttWW1tR0liVHM1NDVrK3dU
            aWlqWGFoZExOZlNmWDRwcndNMWY1OEdEbUZNdEdISGhJdlBibGNOWXNzU2J5ZDNi
            bHhPUkdtcVZ1eEJ5WHVtL29FcFBxRnBCek5UMGNCMllEZXJXTzlTdmFLWTZKSzc5
            Z0FLN1NTOUpyMGZ5TzdNRlVmSmY2M0NyYkI2V0c2R1hOTWdsbzdOM1VDRC95WUQz
            UE8rM2lZMy9Jc291SWtmQTJnZFNUTmlTSDZpVlZVOGFmeThHQXZ4SlQxQTNrOHIz
            TEYxenNFU3oyS3dodXpySks4ZXNpZzV2dUZlU1IwNmVtMHFtdU4vUmZndzdjRVY5
            alVwU3hmeUlLVDZpclpIcTEzWTE0c1VrSDJMTzVic0FmTTRlUXFPNCtveEIxNUtB
            T2ZXRzhrZXkzaFhpUnlqVVhnSEZ4SlZLbDQwYWdDOGdYM3R2UDYrWTQ2Y3ZvN2Vz
            Tmx4N0FiRVhrK0J0SXNLRkRlcTdBajBIaDh5SXY4VlR2WXpGcHM5N0dMUFpkeXcz
            UDlrV0tGQUZ1TEw3ZE1qSzBpclJ5QlRxYkh3M0VqTTdLeEZzOGMxMFVFZUVJU24w
            NzNzN2pvVVdYWTZYQUJoaWluQUNTb0VwV2U5emgwYzlTN2JucE5uSUdCbnpBUGtZ
            UXhneUg3UTBaRjR6Yk40OThTdTl1K0dsclQxTlN1ZVE3SUlLOTNnVTVDTHpYeVFS
            cTNreVhZbm1zc2Y5UUF6RmlhOVlMdG1XaCt4c0FXaEpDczM5ZC9VZGUxZW9jdHFH
            TmN0dWU4eU9laVdHWGN4YlhOTzdSc3ZMZWFuSlNZbmdObmhpakZaeU9uSmIwRjhV
            bWtrbkJVcWFDeXNDOGpCNmQ0SkFzY3U3QzkxYnN5VXRabndaem9RRCtJV0ozckxt
            SWM3cXJOUTVaWDhSYk9kR3JKenFvVGV2WDFBY2tONzdHTkpGMWh4MnpkWnNuTHJY
            SVc1eUVJbWJWeVR3ai9vQktBS3p4Lzl0YU5rNnoxQ1lBKytIOENSU1l5WXJQUQpD
            b1VxNE9lOGg3cVVIcFdtOTZFaGg5dW5RRDE1RHhNQzhRcm5TUXprazFnCi0tLSBD
            N1BZanpKQXNVOGNaUUQyNWZZQkJURXE4UXM3QzVQRkdDU0dadVphbEV3Ct++AfDI
            jZITKnV1ZwMNRBAtl0Nwd3Aam8FdhrgDUUmN4yZ6XDCghZDRuJ5rf7SjMhgQEFd/
            +LcQIdG4/cIAIy0=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1xme50rm3zwqyzhqpjx078eandu987n4n2n6h0g7ludxlfvml4enydqkfjjhkrny0zs6k699076r5n36cjm76c582wk99kfqk8rmr0vsgswlkwlj5tdf0kgxpmr38c34n0pass6kxh9kc62zz8w6u65hcxlwjn0mahx6wqx6xnxpyve25n3qn3qh43f3vlufkrq6ftjt6833uvvkst9y3usyqlvpesj55vn3uwmqmuynsx7wzztgh7qsqz4z2f3unrx2spc935ade7t785rhafgdwpyj59xgf0zj4phsrrwmagzgwhzut9cdsjd44wu8fszahtn8hrf8gaztxz0xyc4khsd6leys2jfysglq98hcn4cchd8lu9wffjsyxt3e9gae8630n20c60g0pygar2jk8u0494d3f85rqg4e2fyq8ver8dut3p9c8rvvrgdy99q23qjfcvddt9canthzxr2jgz8p9khrj5zw2hrksh6r7y63jy94pn3uvwtk8xv09z2cgr0nhjaqp7azqraz2lu55x7ndfpa4sjpftczxe843r9u3pvu0tz5dy9pmgk2tm4dzy8qkgv8y4jlawxxf6fk8lwfk864hkf9ytsxnwg00evy2qf29938xyhkf3qurusuvysr8qws946sfpj7efv9c6px55qjlrp2ggu2vjqfkq0gk79nqf3ec2yy2u86t2yyddqq7yw33g2gygdgzw9h65w9q5zg9xg5m4sfe9rq29m7hp2p5yy4lge0wuetv0dyqvhwvylm6nfrm3skpuu4g78ffcp5mr8lq5nhvfwgjxfyrz0qma8lqqndwcjknhf5nfsj22p98qdmf0qdcfqy4y3zpf4jqzg6f02as24f8pjcns9pzfvyrvjrv87ujjpx2gvnhqgj7zjm2ywqpuusfq3zrguw96vrsm3j27r68spqht0cgr0stxu670cduv2cjahxs3w4y02xh6frnrj3a66rm9s9vn4dj4ygtnzajeqpyapsnqn5t8ag72sgwx6lj02vemskvkpytx5jwz2fpj9qze9qzcdextefvzslgf8qz6pystcy6aaz2zqevkdtz3pe0a9shqktzkmtxkhunrc4qx7fgjdexqc9rd6tnvf4xnyzjqzu5efwv0wdn4z6nh4gh2wf0xlzlzwm5jq4ce3sf3u24e888fp07vxqes5m5e8enue6x9j26w0wxqxfvtdtc9qr6zmcsrrd2np8rd33tq7s9k9ty9lyq4fkle3lyuugz5fkqgjgrqtcmesqeyxhwqu4elf6p4zqe46fqd4xhyy2cj9f2vwjde7eqd4xgr665dynk8xxvt9k2wwvmjh5zxqscql7ru46rpdpf4lj4kl68gdrr5tgt8s4mdy5gzeux797yf58qvmf96p67ne3fpdg4972hguxtvgfxxcu6pry2zxpe659hvaz0yzcdf92nfw4x6vp822dfdjy3w4ckq9hvuyf6xcrqa8g6pfmygtdcuqtuwqu5wx3y0dvg83umg3uv2pftu9cuqvwy3tmmtdgjzaj4z5za82qc049xyfps3zse8yajuzqrxv5mlyse2l0zj0k8rw5569f77ynvsupmffxmg3f5gm2uv4vt2e9t7wcjwxerqug8vjjwcwx932eu60p3ygd297m69853qs622ztkr7ttldm3zxw9jhcxya9444y0znn6qhc8qs8czq39x9f7e6d83xs5sk06zk65g00n0vedz39c572nuu7q4u3k5xnrcd52z3rygycym4wuqnnhx8xeyj6c8am7tmr38uzc400hyz5q92xtp3aualuz0ec40qhuw8ur4fy36pq23e9udw22ampdm8slvue5dg96m09zk3vhzhykhatc5qu2ps3sapzfmv6qt9v2u7fwaw2gktpvxvuaclpy0dqjck0mhuysmexqpsq899xz
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgOUlCQkh3IEJNaklWTG55
            UU9vZk80NEROKy9iYlREWTJ6RXhHTlQ3L1hGeDd5MlJESG1oZmh6SFRFaUwvaGdW
            WGVEZ0x4Q2F3SGRmSWN6dDY4YVdTcnRSSTZZTm8wZwpvODZpRTJPWEFFN2llbHd5
            anM3R05KMEhOTzVIOUNncXR5ZmNNTm4rZlhRCi0tLSBXeXRaYUpzR3JjeFBDOWxn
            Tm9GcUFmczFmc3ZPL1FETWo5TDRBL0Z5NVFNCvCZRA+Zp9Tgk1cyDiJmw4Ee+Ffg
            s4v6oPWJISXHr//+7jCSYAj20rZQtgxjSmau04HU38H82xITfgA4CbL0OEM=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tag1qd5s6fcv5upezjgzv4y39t0kfg0tgalwdfmf3elnccu5u87ctzgmxgmt756
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgSlR3OStBIEJBd2F0SEFV
            YzZ3RFNlM1R1VGprMmpLdng0MU96bkJsdzk0bVEvNEphL0phU3l5bVVRUmNYbzZQ
            VUlvNUF3RFVXYXpEblpIQllSV0hvR0pGRktXWGdEUQovNTMwYzU3TlZWTWh0b3J3
            aGZUWmtmVFc3bm8yM2QwSFVmVmFpWjdQZjU0Ci0tLSBSRmcxY3JVUlFMdnNRUDZh
            Sis1OUFlR1VQSmZ2dW9LNWUzbG1DQzRoSldVCjMPBfMAN3SsxlIPdDyqTPPchQ/Q
            Wlg4H/0CEWrJ5QhpZXs1CK9N0hKowr43EDFIcf0tgGRI8UzdH9yFxUbbhDE=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tag1qwdf600uvtxjw58z48lgkg2txky68jhnlrlr0tjdrkl80gqaume6ynnn57f
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IE8zUXdoUSBBdUdMMVJ0
            SnI3RDJ4ZjJ6UWRBWklKbitFQU5KeGg2bjg4SnBxOEpSSEJ1QgoxVzd3cHAyQ0xz
            NDA0U3NBQmIvQ3dnY1lpV3VHSkxaVVRvUDlKRkxHTi9BCi0tLSA5RVpiSWRiWXJj
            MlVpdUFaSjRnSUdONDhxSWhtZU9namhaMmlTWHJ5N1RNCmXEtVCxZrdc+wtGumnk
            twN7SgIoSiwwtBz9yzlCa8honca6KKZW9KgeRb53ENpYKLr7bTHQR81bJXLthzTo
            i3w=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1se1qwrp2meyq50afmrydcq7ejfwh9hj6zxfwg5wmgg5q5eudavd090v7urw3d5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybVo2VXJIbnNSOTJxdktD
            TVE3aXVSd1cxK2Q5WjluOFMydFlGTVpRN0JVCjkwLzlIMm43MWF6SmlhdGkyZ0x6
            cWJvTzJ3RFQrRnU1Qk5JR0w2YUdySjgKLS0tIEJ2QkdMdGFIeTBVQzBJVEVDR2d4
            NE1NaU9sQlc3TFhRUWJLOFpqelBFQ28KeJ/Qc4bUYp17RcgOJKxUownquKXSUsno
            fW1kGt5Rc5uxHBNns1/MKEQVolLnIkRQR5S/n9kzvQ0MmvPapzgRew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age174yq43fu75xyuf5t92yeekejl6fx84zewy45wqzy538g2qx29clq3gfn3w
    lastmodified: "2026-10-07T14:18:16Z"
    mac: ENC[AES256_GCM,data:/ISNRp/ND+3EcOJQcgz+ii1VgiMnlEi2amWA+qDptp0HRAQ9wzF9a8aBc8/yYorHLGbQj6/3PM2PF9lwNrSnx6tR+W7VHRAfeapxhlcTpWnqMIIHekRM8HLEruN3Jvv+tVEBR29QcpBJMBNwPNmspNo1ahZsWtU+BPUcN8kynk4=,iv:ThHdJBUl0cUDvs4ouoguiZvgZEXjIZ6L2zOPl2mbNcQ=,tag:NxvEMTnjO2jydvyoX5QxmA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
